version: '3.8'
services:
  mysql:
    image: mysql:8.4.3
    container_name: mysql-containerr
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: locationvoituree
    ports:
      - "3307:3306"
    networks:
      - my-network

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-containerr:3306/locationvoituree
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
